FROM openjdk:8-jdk-alpine
VOLUME /tmp
COPY /target/employee-service-0.0.1-SNAPSHOT.jar /usr/src/employee-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/usr/src/employee-service-0.0.1-SNAPSHOT.jar"]
