server:
  port: 8762

spring:
  application:
    name: employee-service

eureka:
    client:
        region: default
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
