server:
  port: 8764

spring:
  application:
    name: auth-service
  datasource:
    #driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    validationQuery: SELECT 1

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


eureka:
    client:
        region: default
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
flyway:
    baselineOnMigrate: true
    locations: db/migration

