server:
  port: 8763

spring:
  application:
    name: department-service

eureka:
    client:
        region: default
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
