server:
  port: 8765

spring:
  application:
    name: edge-service

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /api
  routes:
    employee-service:
      path: /v1/employee/**
      strip-prefix: true
      sensitiveHeaders: Cookie,Set-Cookie
ribbon:
  ServerListRefreshInterval: 5000
  ConnectTimeout: 3000
  ReadTimeout: 60000

