server:
  port: 8762

spring:
  application:
    name: employee-service

eureka:
    client:
        region: default
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    client:
      clientId: employee-service
      clientSecret: password
      accessTokenUri: https://localhost:8764/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
    resource:
      id: employee-service

